In [1]:
from PIL import Image
import os
import numpy as np


In [20]:
with open('tower.jpg','rb') as file:
    # Image함수호출
    img = Image.open(file)
    # 흑백변경 - RGB
    img = img.convert('L')
    # 사이즈 변경
    img = img.resize((28,28))
    # 숫자배열로 변경
    data = np.array(img)
    

In [21]:
data.shape

(28, 28)

In [22]:
data = data/255
print(data)

[[0.01176471 0.01176471 0.01176471 0.01568627 0.01568627 0.01568627
  0.01960784 0.01960784 0.02352941 0.03137255 0.04313725 0.05882353
  0.08627451 0.09803922 0.0745098  0.05490196 0.03921569 0.03137255
  0.02352941 0.01960784 0.01960784 0.01960784 0.01960784 0.02352941
  0.01568627 0.01568627 0.01568627 0.01568627]
 [0.01568627 0.01568627 0.01568627 0.01568627 0.01568627 0.01568627
  0.01960784 0.02352941 0.02745098 0.03137255 0.04313725 0.0627451
  0.14901961 0.29019608 0.08235294 0.0627451  0.04313725 0.03137255
  0.02745098 0.02352941 0.01960784 0.01960784 0.01960784 0.02352941
  0.01568627 0.01568627 0.01568627 0.01568627]
 [0.01568627 0.01176471 0.01568627 0.01568627 0.01568627 0.01568627
  0.01960784 0.02352941 0.02745098 0.03529412 0.04705882 0.05882353
  0.2745098  0.72941176 0.14901961 0.06666667 0.04705882 0.03529412
  0.02745098 0.02352941 0.01960784 0.01960784 0.01960784 0.02352941
  0.01568627 0.01568627 0.01568627 0.01176471]
 [0.01568627 0.01176471 0.01568627 0.0156862

In [18]:
print(data)

[[[  2   3   8]
  [  2   3   8]
  [  2   3   8]
  ...
  [  3   4   7]
  [  2   4   8]
  [  1   4   8]]

 [[  3   4   9]
  [  3   4   9]
  [  3   4   8]
  ...
  [  2   4   7]
  [  2   4   8]
  [  1   5   8]]

 [[  3   4   9]
  [  2   3   8]
  [  3   4   8]
  ...
  [  2   4   7]
  [  2   5   8]
  [  1   4   7]]

 ...

 [[ 41  18   5]
  [ 46  20   5]
  [ 48  22   4]
  ...
  [129  72   9]
  [ 87  46   6]
  [ 46  25   6]]

 [[ 76  38   5]
  [ 82  41   6]
  [ 58  27   6]
  ...
  [ 82  47   6]
  [135  70   7]
  [ 92  44   6]]

 [[ 46  36  10]
  [ 69  42   9]
  [140  76   9]
  ...
  [143  82   8]
  [149  75   8]
  [174  86   5]]]


In [13]:
img.save('test.jpg')